### ISSUE TITLE
maxSize and minSize aren't working for me:

### ISSUE THREAD

**Issue by vidjuheffex** [yyllff/split-pane-react#2]
example can be found here: https://62a261c8d8fc7c6bcee1856c.clutch.host/

 left and right panels have maxs and mins but don't seem to react to that:
 ```js
                       <Pane
                        variants={b.getVariants(undefined)}
                        sx={{
                          height: '100%',
                        }}
                        minSize={230}
                        maxSize={'50%'}
                        key={getKey(report, '20_275', 'pane-3')}
                        data-d={getKey(report, '20_275', 'pane-3')}
                      >
```

could be that i'm rewrapping the component using Styled from mui to accomplish this? but would be somewhat suprising as all other behaviors work

**Comment by yyllff** [comment]
> 

Can you provide more detailed configuration？I can't reproduce this problem here. According to your description.

**Comment by yyllff** [comment]
> example can be found here: https://62a261c8d8fc7c6bcee1856c.clutch.host/
> 
> left and right panels have maxs and mins but don't seem to react to that:
> 
> ```js
>                       <Pane
>                        variants={b.getVariants(undefined)}
>                        sx={{
>                          height: '100%',
>                        }}
>                        minSize={230}
>                        maxSize={'50%'}
>                        key={getKey(report, '20_275', 'pane-3')}
>                        data-d={getKey(report, '20_275', 'pane-3')}
>                      >
> ```
> 
> could be that i'm rewrapping the component using Styled from mui to accomplish this? but would be somewhat suprising as all other behaviors work

Hi @vidjuheffex 
I am glad to help you on this issue.
Could you please provide a Minimal, Reproducible Example?
