### ISSUE TITLE
FR: Disable user-select on .react-split__sash by default

### ISSUE THREAD

**Issue by mhxim** [yyllff/split-pane-react#5]
## Feature request:

Current behavior:
Dragging the divider outside of the split pane selects text.
![split-pane-react bug](https://user-images.githubusercontent.com/50044971/198714801-569e1b9a-be94-4411-8001-6b64e7156bd1.png)

Expected behavior:
Dragging the divider of the split pane doesn't select text.

---
Proposed changes:
Modify the default CSS to disable user-select on the divider:
```
.react-split__sash {
   user-select: none;
}
```

**Comment by yyllff** [comment]
> ## Feature request:
> Current behavior: Dragging the divider outside of the split pane selects text. ![split-pane-react bug](https://user-images.githubusercontent.com/50044971/198714801-569e1b9a-be94-4411-8001-6b64e7156bd1.png)
> 
> Expected behavior: Dragging the divider of the split pane doesn't select text.
> 
> Proposed changes: Modify the default CSS to disable user-select on the divider:
> 
> ```
> .react-split__sash {
>    user-select: none;
> }
> ```
Thank you for your use, but this may not solve your problem。The component can only control the text inside the component not to be selected, and the content outside the component needs to be controlled by you. For example, you can use this component as the root component. I don't know if it can solve your problem.

**Comment by yyllff** [comment]
fixed
